version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hormonal-care-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hormonal
    ports:
      - "3377:3306"
    volumes:
      - hormonal-mysql-data:/var/lib/mysql
    networks:
      - hormonal-care-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:6.0
    container_name: hormonal-care-mongodb
    ports:
      - "27027:27017"
    volumes:
      - hormonal-mongodb-data:/data/db
    networks:
      - hormonal-care-network
    environment:
      - MONGO_INITDB_DATABASE=hormonal_care_communication
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  hormonal-mysql-data:
  hormonal-mongodb-data:

networks:
  hormonal-care-network:
    driver: bridge